### ISSUE TITLE
Bad blocks not implemented when syncing kusama

### ISSUE THREAD

**Issue by gilescope** [paritytech/smoldot#2811] opened 2022-10-02 07:58 UTC
Syncing light client on kusama I get: "Chain specification of ksmcc3 contains a list of bad blocks. Bad blocks are not implemented in the light client."

Obviously it would be really nice if both relay chains are supported. Could this be a good self contained task for someone in the community to jump on and try and implement?

**Comment by tomaka** [comment] 2022-10-04 06:34
Kusama is 100% supported. This warning does in no way indicate that the chain isn't properly supported.

The fact that the "bad blocks" feature isn't implemented is only problematic if the given bad blocks are after the latest finalized blocks.
When the bad blocks are after the latest finalized blocks is also the only situation where this "bad blocks" feature is useful. In other words, if you know how to use feature, then this warning is really important for you, and if you don't know how to use the feature then this warning is completely useless to you.

The appropriate course of action is to remove the list of bad blocks from the chain spec.

**Comment by tomaka** [comment] 2022-10-04 19:43
No matter what, I'm going to close this as a duplicate of https://github.com/paritytech/smoldot/issues/2584

**Closed by tomaka** 2022-10-04 19:43 UTC

**Comment by gilescope** [comment] 2022-10-10 09:02
Maybe the warning could indicate that this is not as bad as it sounds? or just point to this issue?
