### ISSUE TITLE
RPC AccountId deserialization rejects prefixes larger than 1 byte

### ISSUE THREAD

**Issue by arrudagates** [paritytech/smoldot#2685] opened 2022-08-25 14:56 UTC
This line is the main cause of the problem: https://github.com/paritytech/smoldot/blob/main/src/json_rpc/methods.rs#L576
But the lines below also need to be changed to accommodate for more prefix lengths.

**Comment by tomaka** [comment] 2022-08-30 08:51
Closing after #2686 

While the issue isn't "properly" fixed, I think it's "fixed enough" for the foreseeable future.

**Closed by tomaka** 2022-08-30 08:51 UTC
