### ISSUE TITLE
Not connecting to Substrate-based private network

### ISSUE THREAD

**Issue by itzmeanjan** [paritytech/smoldot#451] opened 2021-02-03 08:14 UTC
Hello 👋,

We were attempting to run [`wasm-light-node`](https://github.com/paritytech/smoldot/tree/main/bin/wasm-node/javascript#usage) with a different chain spec, which is chain spec generated from substrate node, running in private network, but it fails to connect to that node saying

```bash
node index.js
[smoldot_js] Loaded chain specs for Test Devnet
[smoldot_js] Initialization complete
[json-rpc] JSON-RPC => "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"system_name\",\"params\":[]}"
[json-rpc] JSON-RPC <= "{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":\"smoldot!\"}"
{"jsonrpc":"2.0","id":1,"result":"smoldot!"}
[connections] Unsupported multiaddr: /ip4/127.0.0.1/tcp/30333
```

where our chain spec has boot address correct. 

We'd love to get some guide here.

**Comment by tomaka** [comment] 2021-02-03 08:51
:wave: 

It is trying to connect to a plain TCP socket, which [isn't supported](https://github.com/paritytech/smoldot/issues/219).

You have to start your Substrate node with `--listen-addr /ip4/0.0.0.0/tcp/30333/ws`, and use `/ip4/127.0.0.1/tcp/30333/ws/p2p/...` as the bootnode.

**Comment by itzmeanjan** [comment] 2021-02-03 09:24
> 👋
> 
> It is trying to connect to a plain TCP socket, which [isn't supported](https://github.com/paritytech/smoldot/issues/219).
> 
> You have to start your Substrate node with `--listen-addr /ip4/0.0.0.0/tcp/30333/ws`, and use `/ip4/127.0.0.1/tcp/30333/ws/p2p/...` as the bootnode. This makes the communications go through a WebSocket layer.

Hey @tomaka thank you very much. I'll try this now.

**Comment by itzmeanjan** [comment] 2021-02-03 10:05
Hello Pierre,

I started chain with proper `--listen-addr` flag & also used correct multi address in chain spec _( by mutating [`westend.json`](https://github.com/paritytech/smoldot/blob/main/bin/westend.json) )_, now it fails saying

```bash
node index.js
[smoldot_js] Loaded chain specs for Test Devnet
[smoldot_js] Initialization complete
[json-rpc] JSON-RPC => "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"system_name\",\"params\":[]}"
[json-rpc] JSON-RPC <= "{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":\"smoldot!\"}"
{"jsonrpc":"2.0","id":1,"result":"smoldot!"}
[connections] Pending(PendingId(PendingId(ConnectionId(0)))) started: ws://127.0.0.1:30333/
[connections] Pending(PendingId(PendingId(ConnectionId(0)))) => Connection(ConnectionId(ConnectionId(ConnectionId(0))))
[network] Connected to 12D3KooWCDrL48MKNdwxzUbuy4VXJkq9HK3HXASQ3vDdtGCvfKxo

file:///home/ubuntu/anjan/light-client/node_modules/smoldot/index.js:87
        throw message;
        ^
panicked at 'not yet implemented', /__w/smoldot/smoldot/src/libp2p/connection/established.rs:964:30
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

Then I tried to use `build-spec` sub command of `substrate-node-template` to export chain specification json file, which when passed during light client initialisation, failed with

```bash
node index.js

file:///home/ubuntu/anjan/light-client/node_modules/smoldot/index.js:87
        throw message;
        ^
Error while opening chain specs: unknown variant `runtime`, expected `raw` at line 14 column 13
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

👆 looks like exported JSON chain spec file format not supported by smoldot. 

I'll also paste exported chain spec, from node-template [ compiled from `master` branch tip ]  👇

```bash
{
  "name": "Development",
  "id": "dev",
  "chainType": "Development",
  "bootNodes": [
    "/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp",
    "/ip4/127.0.0.1/tcp/30333/ws/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
  ],
  "telemetryEndpoints": null,
  "protocolId": null,
  "properties": null,
  "consensusEngine": null,
  "lightSyncState": null,
  "genesis": {
    "runtime": {
      "frameSystem": {
        "changesTrieConfig": null,
        "code": "0x...skipped-due-to-too-long-comment"
      },
      "palletAura": {
        "authorities": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      },
      "palletGrandpa": {
        "authorities": [
          [
            "5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu",
            1
          ]
        ]
      },
      "palletBalances": {
        "balances": [
          [
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            1152921504606846976
          ],
          [
            "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
            1152921504606846976
          ],
          [
            "5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY",
            1152921504606846976
          ],
          [
            "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc",
            1152921504606846976
          ]
        ]
      },
      "palletSudo": {
        "key": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
      }
    }
  }
}
```

**Comment by itzmeanjan** [comment] 2021-02-03 10:11
There's a clear field name difference in 👆 chain spec file, when compared to which is present in [`westend.json`](https://github.com/paritytech/smoldot/blob/main/bin/westend.json).

**Comment by tomaka** [comment] 2021-02-03 10:39
> I started chain with proper --listen-addr flag & also used correct multi address in chain spec ( by mutating westend.json ), now it fails saying

This is indeed most likely caused by a mismatch in the chain specs (in the `protocolId` in particular).

> Is there any other way to export chain spec from substrate node-template ?

You need to update the chain specs with `--raw`. This will convert all these human-readable values (which smoldot can't understand) into raw key and values.

**Comment by itzmeanjan** [comment] 2021-02-04 04:08
> You need to update the chain specs with --raw. This will convert all these human-readable values (which smoldot can't understand) into raw key and values.

Oh thanks, let me try this one.

**Comment by itzmeanjan** [comment] 2021-02-05 06:32
Hello Pierre,

After exporting chain spec from substrate node with `--raw` flag, I got 👇

```json
{
  "name": "Local Testnet",
  "id": "local_testnet",
  "chainType": "Local",
  "bootNodes": [
    "/ip4/127.0.0.1/tcp/30333/ws/p2p/12D3KooWQjkPyG8cT9SXo6sg8sZXFq6FhsVfJ3NPZpRazQWmDNBs"
  ],
  "telemetryEndpoints": null,
  "protocolId": null,
  "properties": null,
  "consensusEngine": null,
  "lightSyncState": null,
  "genesis": {
    "raw": {
      "top": {
        "0x3f1467a096bcd71a5b6a0c8155e20810878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0x5c0d1176a568c1f92944340dbfed9e9c530ebca703c85910e7164cb7d1c9e47b": "0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "0xc2261276cc9d1f8598ea4b6a74b15c2f878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9e5e802737cce3a54b0bc9e3d3e6be26e306721211d5404bd9da88e0204360a1a9ab8b87c66c1bc2fcdd37f3c2222cc20": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x3a636f6465": "<skipped-here-intentionally>",
        "0x26aa394eea5630e07c48ae0c9558cef75684a022a34dd8bfa2baaf44f172b710": "0x01",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da96f2e33376834a63c86a195bcf685aebbfe65717dad0447d715f660a0a58411de509b42e6efb8375f562f58a554d5860e": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x5c0d1176a568c1f92944340dbfed9e9c878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9de1e86a9a8c739864cf3cc5ec2bea59fd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x177e6857fb1d0e409376122fee3ad4f8878d434d6125b40443fe11fd292d13a4": "0x02000000",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da94f9aea1afa791265fae359272badc1cf8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9b0edae20838083f2cde1c4080db8cf8090b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x3a65787472696e7369635f696e646578": "0x00000000",
        "0xc2261276cc9d1f8598ea4b6a74b15c2f57c875e4cff74148e4628f264b974c80": "0x00000000000000c00000000000000000",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9007cbc1270b5b091758f9c42f5915b3e8ac59e11963af19174d0b94d5d78041c233f55d2e19324665bafdfb62925af2d": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x5f9cc45b7a00c5899361e1c6099678dc878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9f3f619a1c2956443880db9cc9a13d058e860f1b1c7227f7c22602f53f15af80747814dffd839719731ee3bba6edc126c": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0xc2261276cc9d1f8598ea4b6a74b15c2f308ce9615de0775a82f8a94dc3d285a1": "0x01",
        "0x26aa394eea5630e07c48ae0c9558cef7a44704b568d21667356a5a050c118746b4def25cfda6ef3a00000000": "0x4545454545454545454545454545454545454545454545454545454545454545",
        "0x26aa394eea5630e07c48ae0c9558cef78a42f33323cb5ced3b44dd825fda9fcc": "0x4545454545454545454545454545454545454545454545454545454545454545",
        "0x3a6772616e6470615f617574686f726974696573": "0x010888dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee0100000000000000d17c2d7823ebf260fd138f2d7e27d114c0145d968b5ff5006125f2414fadae690100000000000000",
        "0x57f8dc2f5ab09467896f47300f042438878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da98578796c363c105114787203e4d93ca6101191192fc877c24d725b337120fa3edc63d227bbc92705db1e2cb65f56981a": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x26aa394eea5630e07c48ae0c9558cef7f9cce9c888469bb1a0dceaa129672ef8": "0x04346e6f64652d74656d706c617465",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da932a5935f6edc617ae178fef9eb1e211fbe5ddb1579b72e84524fc29e78609e3caf42e85aa118ebfe0b0ad404b5bdd25f": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0xbd2a529379475088d3e29a918cd47872878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9edeaa42c2163f68084a988529a0e2ec5e659a7a1628cdd93febc04a4e0646ea20e9f5f0ce097d9a05290d4a9e054df4e": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x2371e21684d2fae99bcb4d579242f74ad47cb8f5328af743ddfb361e7180e7fcbb1bdbcacd6ac9340000000000000000": "0x00000000",
        "0x2371e21684d2fae99bcb4d579242f74a8a2d09463effcc78a22d75b9cb87dffc": "0x0000000000000000",
        "0x26aa394eea5630e07c48ae0c9558cef7878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0xf0c365c3cf59d671eb72da0e7a4113c4878d434d6125b40443fe11fd292d13a4": "0x02000001",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da923a05cabf6d3bde7ca3ef0d11596b5611cbd2d43530a44705ad088af313e18f80b53ef16b36177cd4b77b846f2a5f07c": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9b321d16960ce1d9190b61e2421cc60131e07379407fecc4b89eb7dbd287c2c781cfb1907a96947a3eb18e4f8e7198625": "0x000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "0x57f8dc2f5ab09467896f47300f0424385e0621c4869aa60c02be9adcc98a0d1d": "0x08d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48"
      },
      "childrenDefault": {}
    }
  }
}
```

When started `node-template`, it kept mining & light client first got connected & then disconnected as shown 👇

```bash
 node index.js
[smoldot_js] Loaded chain specs for Local Testnet
[smoldot_js] Initialization complete
[json-rpc] JSON-RPC => "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"system_name\",\"params\":[]}"
[json-rpc] JSON-RPC <= "{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":\"smoldot!\"}"
{"jsonrpc":"2.0","id":1,"result":"smoldot!"}
[connections] Pending(PendingId(PendingId(ConnectionId(0)))) started: ws://127.0.0.1:30333/
[connections] Pending(PendingId(PendingId(ConnectionId(0)))) => Connection(ConnectionId(ConnectionId(ConnectionId(0))))
[network] Connected to 12D3KooWENdS7AEhbY39CeBdehVX6tA2yP2PBRtBdLvqKRRoNKrp
[network] Connection(12D3KooWENdS7AEhbY39CeBdehVX6tA2yP2PBRtBdLvqKRRoNKrp) => ChainConnected(0, 6, 0x05c2…3242)
[network] Connection(12D3KooWENdS7AEhbY39CeBdehVX6tA2yP2PBRtBdLvqKRRoNKrp) <= BlocksRequest(BlocksRequestConfig { start: Number(1), desired_count: 128, direction: Ascending, fields: BlocksRequestFields { header: true, body: false, justification: true } })
[network] Connection(12D3KooWENdS7AEhbY39CeBdehVX6tA2yP2PBRtBdLvqKRRoNKrp) => ChainDisconnected(0)
[smoldot_js] Database save start
```

What do you think might be reason behind it ?

**Comment by tomaka** [comment] 2021-02-05 06:53
The networking side is unfortunately one of the weak point of the code right, and we're not logging much.
Please make sure that you indeed have the same chain specs on the Substrate node by passing `--chain ./foo.json` for example.

**Comment by itzmeanjan** [comment] 2021-02-05 07:51
Yes I've run substrate node with `--chain chain-spec.json` but still light client not connecting. 

Do you have any example where it was tested with substrate based nodes ?

**Comment by tomaka** [comment] 2021-02-07 19:14
> Do you have any example where it was tested with substrate based nodes ?

All the JSON files in `bin` are Substrate-based chains.

I'll need to see the `sub-libp2p` logs of your node to understand what's going on (`--log sub-libp2p` when running the node).

**Comment by tomaka** [comment] 2021-03-23 11:03
Closing since there's nothing actionable.

**Closed by tomaka** 2021-03-23 11:03 UTC
