### ISSUE TITLE
Error Occured

### ISSUE THREAD

**Issue by MohammadAbuzar945** [paritytech/smoldot#2784] opened 2022-09-27 05:10 UTC
Internal error in smoldot: Error: panicked at 'called `Option::unwrap()` on a `None` value', /__w/smoldot/smoldot/src/libp2p/connection/established/single_stream.rs:859:14

**Comment by tomaka** [comment] 2022-09-27 06:15
Thanks. Closing as duplicate of https://github.com/paritytech/smoldot/issues/2740

**Closed by tomaka** 2022-09-27 06:15 UTC
